name = "HrlMuJoCoEnvs"
uuid = "b8da5b23-2d8f-482c-ba9f-9eec9bcb73c4"
authors = ["sash-a <reallysasha@gmail.com>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LyceumBase = "db31fed1-ca1e-4084-8a49-12fae1996a55"
LyceumMuJoCo = "48b9757e-04b8-4dbf-b6ed-75c13d9e4026"
LyceumMuJoCoViz = "409fd311-7925-44f6-a514-6be572b34fdd"
MuJoCo = "93189219-7048-461c-94ec-443a161ed927"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Shapes = "175de200-b73b-11e9-28b7-9b5b306cec37"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"
